# Generated by Django 4.2.7 on 2024-04-17 01:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("front_end", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Goal",
        ),
    ]
