# Generated by Django 4.2.7 on 2024-04-18 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("front_end", "0002_rename_category_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goal",
            name="duration",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goal",
            name="notes",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="goal",
            name="satisfaction",
            field=models.IntegerField(
                choices=[
                    (1, "Very Unsatisfied"),
                    (2, "Unsatisfied"),
                    (3, "Neutral"),
                    (4, "Satisfied"),
                    (5, "Very Satisfied"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
