# Generated by Django 4.2.7 on 2024-04-25 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("front_end", "0003_goal_created_at_goal_duration_goal_notes_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Goal",
            new_name="Meditation",
        ),
    ]
