# Generated by Django 4.2.7 on 2024-04-26 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("front_end", "0004_rename_goal_meditation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meditation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
